import type { FilmDirector, MusicVideoDirector } from "./director-types"

export const curatedFilmDirectors: FilmDirector[] = [
  {
    id: "nolan",
    domain: "film",
    name: "Christopher Nolan",
    description: "IMAX-scale mind-bending epics with intricate narrative structures",
    visualLanguage: "Large-format cinematography with practical effects, geometric compositions, and sweeping camera movements. Prefers wide shots and deep focus to show spatial relationships. Uses rotating and tilting cameras for disorientation.",
    colorPalette: "Cool blues and warm ambers, high contrast lighting, often desaturated with selective color pops",
    narrativeFocus: "Non-linear storytelling, puzzle-box narratives, time manipulation, and layered reality",
    category: "Contemporary",
    tags: ["cerebral", "ambitious", "technical", "non-linear"],
    disciplines: ["composition", "camera-movement", "editing-rhythm", "world-building"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "kubrick",
    domain: "film",
    name: "Stanley Kubrick",
    description: "Meticulous perfectionist known for symmetrical compositions and psychological depth",
    visualLanguage: "Symmetrical framing, one-point perspective, slow zoom-ins, and tracking shots. Obsessive attention to geometric precision and architectural spaces. Static wide shots that let scenes breathe.",
    colorPalette: "Stark contrasts, bold primary colors, clinical whites and sterile environments",
    narrativeFocus: "Psychological horror, human nature's dark side, institutional critique, existential themes",
    category: "Classic",
    tags: ["symmetrical", "meticulous", "psychological", "geometric"],
    disciplines: ["composition", "world-building", "tone-mood", "performance-direction"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "wes-anderson",
    domain: "film",
    name: "Wes Anderson",
    description: "Whimsical auteur with distinctive symmetrical style and quirky characters",
    visualLanguage: "Perfect symmetry, flat compositions, lateral tracking shots, and meticulously designed sets. Uses planimetric shots and dollhouse-like framing. Static camera with precise movements.",
    colorPalette: "Pastel palettes, vintage color schemes, carefully coordinated production design",
    narrativeFocus: "Quirky family dynamics, coming-of-age stories, melancholic nostalgia, deadpan humor",
    category: "Auteur",
    tags: ["symmetrical", "whimsical", "precise", "nostalgic"],
    disciplines: ["composition", "world-building", "color-lighting", "performance-direction"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "scorsese",
    domain: "film",
    name: "Martin Scorsese",
    description: "Master of kinetic energy and character-driven crime narratives",
    visualLanguage: "Dynamic camera movements, tracking shots, freeze frames, and rapid montages. Uses handheld cameras for intimacy and Steadicam for fluid motion. Loves long takes and 360-degree shots.",
    colorPalette: "Rich reds and deep shadows, warm tungsten lighting, high contrast noir aesthetics",
    narrativeFocus: "Character psychology, moral ambiguity, violence and redemption, urban environments",
    category: "Contemporary",
    tags: ["kinetic", "character-driven", "intense", "urban"],
    disciplines: ["camera-movement", "editing-rhythm", "performance-direction", "tone-mood"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "fincher",
    domain: "film",
    name: "David Fincher",
    description: "Dark psychological thrillers with clinical precision and digital perfection",
    visualLanguage: "Locked-off cameras, digital intermediate color grading, invisible VFX, and methodical compositions. Uses motion control rigs and precise camera movements. Clean, clinical framing.",
    colorPalette: "Desaturated greens and yellows, cool color temperature, high contrast shadows",
    narrativeFocus: "Psychological manipulation, technology's dark side, obsessive characters, systemic corruption",
    category: "Contemporary",
    tags: ["clinical", "precise", "dark", "methodical"],
    disciplines: ["composition", "color-lighting", "tone-mood", "editing-rhythm"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "tarantino",
    domain: "film",
    name: "Quentin Tarantino",
    description: "Pop culture-infused genre mashups with distinctive dialogue and violence",
    visualLanguage: "Low angles, crash zooms, trunk shots, and dynamic framing. Uses extreme close-ups and wide shots for tension. Loves Dutch angles and unconventional perspectives.",
    colorPalette: "Saturated colors, warm film stock, high contrast lighting with deep shadows",
    narrativeFocus: "Non-linear narratives, pop culture references, revenge stories, genre deconstruction",
    category: "Contemporary",
    tags: ["stylized", "violent", "pop-culture", "genre-bending"],
    disciplines: ["composition", "editing-rhythm", "performance-direction", "tone-mood"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "villeneuve",
    domain: "film",
    name: "Denis Villeneuve",
    description: "Atmospheric sci-fi epics with emotional depth and stunning visuals",
    visualLanguage: "Wide establishing shots, shallow depth of field, floating camera movements, and architectural framing. Uses negative space and silhouettes. Prefers natural lighting and practical locations.",
    colorPalette: "Muted earth tones, orange and teal contrasts, atmospheric haze and fog",
    narrativeFocus: "Existential themes, human connection, environmental storytelling, emotional intimacy",
    category: "Contemporary",
    tags: ["atmospheric", "contemplative", "epic", "emotional"],
    disciplines: ["composition", "world-building", "color-lighting", "tone-mood"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "coen-brothers",
    domain: "film",
    name: "Coen Brothers",
    description: "Darkly comic genre exercises with meticulous craft and ironic detachment",
    visualLanguage: "Wide-angle lenses, static compositions, symmetrical framing, and deliberate camera movements. Uses extreme wide shots and tight close-ups. Loves overhead shots and unusual angles.",
    colorPalette: "Period-appropriate palettes, naturalistic lighting, often desaturated with selective warmth",
    narrativeFocus: "Dark comedy, moral ambiguity, genre pastiche, existential absurdity",
    category: "Auteur",
    tags: ["darkly-comic", "meticulous", "genre-savvy", "ironic"],
    disciplines: ["composition", "tone-mood", "world-building", "editing-rhythm"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
]

export const curatedMusicVideoDirectors: MusicVideoDirector[] = [
  {
    id: "hype-williams",
    domain: "music-video",
    name: "Hype Williams",
    description: "Pioneering hip-hop visionary known for surreal imagery and innovative techniques",
    visualHallmarks: "Fish-eye lenses, metallic surfaces, surreal environments, slow-motion sequences, and futuristic aesthetics. Uses reflective materials, unusual camera angles, and dreamlike imagery.",
    narrativeStyle: "Abstract and symbolic storytelling, often non-linear with emphasis on mood and atmosphere over literal narrative",
    pacingAndEnergy: "Hypnotic and dreamlike, building tension through visual repetition and surreal imagery",
    genres: ["Hip-Hop", "R&B", "Rap"],
    category: "Hip-Hop & R&B Visionaries",
    tags: ["surreal", "innovative", "futuristic", "iconic"],
    disciplines: ["visual-effects", "performance", "fashion-styling", "editing"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "michel-gondry",
    domain: "music-video",
    name: "Michel Gondry",
    description: "Inventive French director known for creative practical effects and whimsical concepts",
    visualHallmarks: "Practical effects, stop-motion animation, split-screens, and handmade aesthetics. Uses creative transitions, morphing effects, and playful visual tricks without heavy CGI.",
    narrativeStyle: "Whimsical and imaginative storytelling with childlike wonder and creative problem-solving",
    pacingAndEnergy: "Playful and inventive, with surprising visual transitions that maintain viewer engagement",
    genres: ["Alternative", "Indie", "Electronic", "Pop"],
    category: "Avant-Garde & Indie Innovators",
    tags: ["inventive", "whimsical", "practical-effects", "creative"],
    disciplines: ["visual-effects", "narrative", "editing", "performance"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "spike-jonze",
    domain: "music-video",
    name: "Spike Jonze",
    description: "Innovative storyteller blending surreal concepts with emotional authenticity",
    visualHallmarks: "Handheld cameras, natural lighting, unconventional locations, and seamless blend of reality and fantasy. Uses long takes and immersive environments.",
    narrativeStyle: "Emotionally resonant stories with surreal elements, often exploring themes of connection and isolation",
    pacingAndEnergy: "Contemplative yet dynamic, building emotional crescendos through visual storytelling",
    genres: ["Alternative", "Indie", "Hip-Hop", "Electronic"],
    category: "Cinematic Storytellers",
    tags: ["innovative", "emotional", "surreal", "authentic"],
    disciplines: ["narrative", "performance", "editing", "live-action"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "david-fincher-mv",
    domain: "music-video",
    name: "David Fincher (Music Videos)",
    description: "Precision-crafted visuals with dark psychological undertones",
    visualHallmarks: "Locked-off cameras, digital color grading, methodical compositions, and clinical precision. Uses motion control and invisible effects for seamless visuals.",
    narrativeStyle: "Dark psychological narratives with emphasis on character psychology and atmospheric tension",
    pacingAndEnergy: "Controlled and methodical, building tension through precise editing and visual restraint",
    genres: ["Alternative", "Industrial", "Rock"],
    category: "Cinematic Storytellers",
    tags: ["clinical", "precise", "dark", "methodical"],
    disciplines: ["visual-effects", "editing", "performance", "narrative"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "chris-cunningham",
    domain: "music-video",
    name: "Chris Cunningham",
    description: "Disturbing and beautiful visuals that push the boundaries of the medium",
    visualHallmarks: "Body horror aesthetics, digital manipulation, stark lighting, and unsettling imagery. Uses prosthetics, CGI, and practical effects to create disturbing beauty.",
    narrativeStyle: "Abstract and often disturbing narratives that explore themes of technology, identity, and transformation",
    pacingAndEnergy: "Intense and unsettling, with moments of beautiful horror that create lasting impact",
    genres: ["Electronic", "IDM", "Experimental"],
    category: "Avant-Garde & Indie Innovators",
    tags: ["disturbing", "beautiful", "experimental", "boundary-pushing"],
    disciplines: ["visual-effects", "editing", "performance", "fashion-styling"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "joseph-kahn",
    domain: "music-video",
    name: "Joseph Kahn",
    description: "High-energy pop spectacles with cinematic production values",
    visualHallmarks: "High-speed cameras, elaborate sets, costume changes, and cinematic lighting. Uses rapid editing, multiple locations, and large-scale production design.",
    narrativeStyle: "Pop culture narratives with references to films, fashion, and contemporary culture",
    pacingAndEnergy: "High-energy and fast-paced, with constant visual stimulation and rapid-fire editing",
    genres: ["Pop", "Hip-Hop", "R&B"],
    category: "Pop & Spectacle Auteurs",
    tags: ["high-energy", "cinematic", "pop-culture", "spectacular"],
    disciplines: ["performance", "fashion-styling", "editing", "visual-effects"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "dave-meyers",
    domain: "music-video",
    name: "Dave Meyers",
    description: "Surreal pop visuals with bold colors and imaginative concepts",
    visualHallmarks: "Vibrant colors, surreal set pieces, creative costumes, and imaginative visual effects. Uses bold production design and fantastical environments.",
    narrativeStyle: "Fantastical and surreal narratives that blend reality with imagination",
    pacingAndEnergy: "Dynamic and colorful, with surprising visual moments that maintain excitement",
    genres: ["Pop", "Hip-Hop", "R&B", "Alternative"],
    category: "Pop & Spectacle Auteurs",
    tags: ["surreal", "colorful", "imaginative", "bold"],
    disciplines: ["visual-effects", "fashion-styling", "performance", "editing"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "director-x",
    domain: "music-video",
    name: "Director X",
    description: "Urban storytelling with authentic street aesthetics and powerful performances",
    visualHallmarks: "Handheld cameras, natural lighting, urban locations, and authentic street aesthetics. Uses dynamic camera movements and intimate framing.",
    narrativeStyle: "Authentic urban narratives with focus on community, struggle, and triumph",
    pacingAndEnergy: "Raw and authentic, with powerful emotional moments and energetic performance sequences",
    genres: ["Hip-Hop", "R&B", "Rap"],
    category: "Hip-Hop & R&B Visionaries",
    tags: ["authentic", "urban", "powerful", "street"],
    disciplines: ["performance", "narrative", "live-action", "editing"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "melina-matsoukas",
    domain: "music-video",
    name: "Melina Matsoukas",
    description: "Visually striking narratives with strong social and political themes",
    visualHallmarks: "Bold cinematography, striking compositions, rich colors, and powerful imagery. Uses symbolic visuals and strong production design.",
    narrativeStyle: "Socially conscious narratives that address political themes and cultural identity",
    pacingAndEnergy: "Powerful and impactful, building emotional and political resonance through visual storytelling",
    genres: ["Hip-Hop", "R&B", "Pop"],
    category: "Hip-Hop & R&B Visionaries",
    tags: ["political", "striking", "powerful", "conscious"],
    disciplines: ["narrative", "performance", "fashion-styling", "editing"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
  {
    id: "floria-sigismondi",
    domain: "music-video",
    name: "Floria Sigismondi",
    description: "Dark artistic visions with fashion-forward aesthetics and gothic beauty",
    visualHallmarks: "High contrast lighting, fashion photography aesthetics, gothic imagery, and artistic compositions. Uses dramatic makeup, costumes, and set design.",
    narrativeStyle: "Dark artistic narratives with themes of beauty, decay, and transformation",
    pacingAndEnergy: "Moody and atmospheric, with moments of intense beauty and dark elegance",
    genres: ["Alternative", "Rock", "Pop", "Electronic"],
    category: "Avant-Garde & Indie Innovators",
    tags: ["gothic", "fashion-forward", "artistic", "dark"],
    disciplines: ["fashion-styling", "visual-effects", "performance", "editing"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    isCustom: false,
  },
]
